# Generated by Django 4.1 on 2022-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media/about/')),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
            },
        ),
    ]
